# Generated by Django 2.1.7 on 2019-04-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagofwords', '0002_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
