# Generated by Django 2.1.7 on 2019-04-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagofwords', '0003_delete_sentiment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Sentiment',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='word_text',
            new_name='unit',
        ),
    ]
