# Generated by Django 2.1.7 on 2019-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagofwords', '0005_auto_20190414_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='negativity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='objectivity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='positivity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
